# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-29 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medium_side', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('longest_side', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('smallest_side', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('size_tier', models.CharField(max_length=25)),
                ('order_date', models.DateField(null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('period', models.CharField(max_length=25)),
            ],
        ),
    ]
